disabled = false
languageCode = "zh-cn"
languageName = "ä¸­æ–‡"
weight = 1
title = "hujiachengçš„æŠ€æœ¯åšå®¢"

[params]
  displayName = "ZH"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/avatar.png"
  description = "åˆ†äº«å‰ç«¯å¼€å‘ã€åç«¯æŠ€æœ¯ã€æ¶æ„è®¾è®¡ä¸ç¼–ç¨‹å®è·µçš„ä¸ªäººæŠ€æœ¯åšå®¢"

[params.author]
  name = "hujiacheng"
  image = "https://avatars.githubusercontent.com/u/124435001?v=4"
  headline = "ğŸ§‘â€ğŸ’» å‰ç«¯å·¥ç¨‹å¸ˆ | ğŸ’ª åŠªåŠ›å˜å¾—æ›´å¥½"
  bio = "Front-end Developer / Strive To Become Better"
  links = [
    { github = "https://github.com/BINGWU2003" },
    { email = "mailto:hujiacheng2003@163.com" },
  ]
