# -- Main Menu --

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "分类"
  pageRef = "categories"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/BINGWU2003"
  weight = 200

# -- Footer Menu --
[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 10
