# -- Main Menu --

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "分类"
  pageRef = "categories"
  weight = 30

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 40

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/BINGWU2003"
  weight = 200

[[main]]
  identifier = "blowfish"
  pre = "globe"
  url = "https://blowfish.page"
  weight = 210

# -- Footer Menu --
[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 10
