# -- Theme Options --
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true

mainSections = ["posts"]

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false

defaultBackgroundImage = "/img/background.svg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

fingerprintAlgorithm = "sha512"

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  homepageImage = "img/background.svg"
  showRecent = true
  showRecentItems = 12
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 6
  showTaxonomies = true
  showWordCount = true
  sharingLinks = ["twitter", "reddit", "whatsapp", "telegram", "email"]
  showZenMode = true

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = true
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
